# Notebook to test random Code chunks.
The ultimate Sandbox

In [1]:
import numpy as np
import os as os
import sys as sys
import multiprocessing as mp
import pandas as pd
import socket

### Pick the right path (whether on cluster or at home)
socket_name = socket.gethostname()
print(socket_name)
if socket_name == "VioletQueen":
    path = "/home/harald/git/HAPSBURG/"   # The Path on Harald's machine
elif socket_name.startswith("midway2"):
    print("Midway jnovmbre partition detected.")
    path = "/project2/jnovembre/hringbauer/HAPSBURG/"  # The Path on Midway Cluster
else: 
    raise RuntimeWarning("Not compatible machine. Check!!")
    
os.chdir(path)  # Set the right Path (in line with Atom default)

sys.path.append("./Python3/")  # Since now we are in the Root Directory
from hmm_inference import HMM_Analyze   # Do not move. Should be after sys.path..
#sys.path.append("./Python3/create1000G_Mosaic/")  # Since now we are in the Root Directory
#from createMosaicsMulti import Mosaic_1000G_Multi  # Import the object that can create the Multiruns

print(os.getcwd()) # Show the current working directory. Should be HAPSBURG/Notebooks/ParallelRuns
print(f"CPU Count: {mp.cpu_count()}")

midway2-0401.rcc.local
Midway jnovmbre partition detected.
/project2/jnovembre/hringbauer/HAPSBURG
CPU Count: 28


## Test Own Example Package

In [ ]:
from example_pkg.addition import add

In [20]:
add(10, 20)

30


30

# Test direct shell code on cluster

### Figure out the deal with Kendras SNP

In [15]:
dfs = pd.read_csv("./Data/Sirak20/v421_CaribIllu1000GancSam_bySite_PAM.snp", sep="\s+", header=None)
dfs.columns = ["SNP", "chr", "map",
                          "pos", "ref", "alt"]  # Set the Columns

dfo = pd.read_csv("./Data/Olalde19/Olalde_et_al_genotypes.snp", sep="\s+", header=None)
dfo.columns = ["SNP", "chr", "map",
                          "pos", "ref", "alt"]  # Set the Columns

In [23]:
same = dfo["pos"]==dfs["pos"]
print(f"Same Position: {np.sum(same)} / {len(same)}")

Same Position: 1233013 / 1233013


In [26]:
samer = dfo["ref"]==dfs["ref"]
print(f"Same Ref: {np.sum(samer)} / {len(samer)}")

Same Ref: 303366 / 1233013


In [27]:
samea = dfo["alt"]==dfs["alt"]
print(f"Same Ref: {np.sum(samea)} / {len(samea)}")

Same Ref: 303366 / 1233013


In [28]:
dfs.loc[~samer, 'ref'], dfs.loc[~samea, 'alt'] = dfs.loc[~samer, 'alt'], dfs.loc[~samer, 'ref']  # Flip Ref and Alt where mismatch

In [29]:
same = dfo["pos"]==dfs["pos"]
print(f"Same Position: {np.sum(same)} / {len(same)}")

Same Position: 1233013 / 1233013


In [30]:
samea = dfo["alt"]==dfs["alt"]
print(f"Same Ref: {np.sum(samea)} / {len(samea)}")

Same Ref: 1233013 / 1233013


In [2]:
os.chdir("./PackagesSupport/cluster_runs/Marcus_callROH/")  # Set the right Path (in line with Atom default)
print(os.getcwd())

/project2/jnovembre/hringbauer/HAPSBURG/PackagesSupport/cluster_runs/Marcus_callROH


In [ ]:
!python3 run_individual_Marcus.py 0

In [57]:
c=np.arange(5)

In [117]:
a = np.zeros(5).astype("bool")
a[1]=True
a[2]=True

In [118]:
b = np.zeros(5).astype("bool")
#b[0]=True
#b[3]=True
b[0]=True

In [119]:
np.cumsum(a + b)

array([1, 2, 3, 3, 3])

In [120]:
np.cumsum(a) + np.cumsum(b)

array([1, 2, 3, 3, 3])

In [144]:
a = np.array([[1,1,1],[2,2,2]])
a

array([[1, 1, 1],
       [2, 2, 2]])

In [145]:
c=np.array([0,2])
c=[]

In [146]:
a[1,:], a[0,:]= a[0,:], a[1,:]
a

array([[1, 1, 1],
       [1, 1, 1]])

In [147]:
print("test")

test


In [153]:
a=np.zeros(3, dtype="bool")
a[[]]=True

In [154]:
a

array([False, False, False])