In [1]:
import numpy as np
import os as os
import sys as sys
import multiprocessing as mp
import pandas as pd
import socket
import shutil as shutil

socket_name = socket.gethostname()
print(socket_name)
if socket_name == "VioletQueen":
    path = "/home/harald/git/HAPSBURG/"   # The Path on Harald's machine
elif socket_name.startswith("midway2"):
    print("Midway jnovmbre partition detected.")
    path = "/project2/jnovembre/hringbauer/HAPSBURG/"  # The Path on Midway Cluster
else: 
    raise RuntimeWarning("Not compatible machine. Check!!")

os.chdir(path)  # Set the right Path (in line with Atom default)
print(os.getcwd()) # Show the current working directory. Should be HAPSBURG/Notebooks/ParallelRuns
print(f"CPU Count: {mp.cpu_count()}")

#sys.path.append("./package/")  # Since now we are in the Root Directory.
sys.path.insert(0,"./package/")  # Hack to get developer package
#from hmm_inference import HMM_Analyze   # Do not move. Should be after sys.path..

#from PackagesSupport.parallel_runs.helper_functions import prepare_path, create_folders, postprocess_iid
from hapsburg.PackagesSupport.hapsburg_run import hapsb_chrom
from hapsburg.PackagesSupport.parallel_runs.helper_functions import multi_run, split_up_roh_df  # Parallel Runs and forward ground truth
from hapsburg.PackagesSupport.pp_individual_roh_csvs import merge_called_blocks

midway2-0401.rcc.local
Midway jnovmbre partition detected.
/project2/jnovembre/hringbauer/HAPSBURG
CPU Count: 28


### Run the test case 
Vary Parameters and the suffixes to explore parameter range

In [3]:
### Prepare Parameter files and run
#### Create the parameters array for the starmap:
iids = ["iid" + str(i) for i in range(0,100)]   # List of iids to iterate over
### Create list of IIDs and of Folders

ch = 3 # For test case here: Only do Chromosome #3
n_ref = 2504  # 2504 All 503 Europe/TSI 504 EAS
diploid_ref = True
save = True
save_fp = False

#exclude_pops = ["TSI", ]
exclude_pops = []
e_model = "readcount"
p_model = "MosaicHDF5"  
readcounts = True
destroy_phase = False
post_model = "Standard"
h5_path1000g = "./Data/1000Genomes/HDF5/1240kHDF5/all1240gzip/chr" # Switch: Eur1240chr for classic
meta_path_ref = "./Data/1000Genomes/Individuals/meta_df_all.csv"  # meta_df.csv for full 1000G
base_path="./Simulated/1000G_Mosaic/TSI5/lambda_rc1.0/" # Simulated Mosaics
#base_path="./Simulated/1000G_Mosaic/CLM/" # Simulated Mosaics

roh_in = 1   #1  New: 0.1
roh_out = 20 # 20 Good: 10
roh_jump = 300
e_rate = 0.01  # The Error Rate
e_rate_ref = 0.0
max_gap = 0.0 # Gap Merging. In M
#cutoffs = [0.9, 0.99, 0.9999, 0.99999]
cutoffs = [0.999]
l_cutoff = 0.02
logfile = True
#lengths = [0, 2, 4, 6, 8, 10] # Which Block Lengths to test
lengths = [4,]  # Relevant ones for key performance testing
#prefix_out = "eas_ref/" # Check as well below in loop!!!

folders = [base_path + "ch" + str(ch) + "_" + str(int(l)) + "cm/" for l in lengths]  # Prepare Length folders. # "cm/missing/5/"

#########################################################
### Create the List of Parameter Lists (input for starmap)
prms = []
for f in folders: 
    path_targets = f + "data.h5"
    base_out_folder = os.path.join(f, "output", "")
    
    for cutoff in cutoffs:
        #prefix_out = str(cutoff).replace(".", "") + "/"
        prefix_out = "default/"  # "eas_ref.jump500/"
    
        for iid in iids:
            new_par = [iid, ch, save, save_fp, n_ref, diploid_ref, exclude_pops, e_model, p_model, readcounts, destroy_phase,
            post_model, path_targets, h5_path1000g, meta_path_ref, base_out_folder, prefix_out,
            roh_in, roh_out, roh_jump, e_rate, e_rate_ref, max_gap, cutoff, l_cutoff, logfile]
            prms.append(new_par)  # Append to the Parameters
        
assert(len(prms[0])==26)   # Sanity Check
print(len(prms))

100


In [ ]:
prms[0]

### Test Run of single indivdual
Takes about 45 seconds for one run

In [ ]:
%%time
assert(logfile==False)
multi_run(hapsb_chrom, [prms[2]], processes = 1)

In [7]:
np.sum(a * b, axis = 2)

array([[ 5, 14],
       [23, 32],
       [41, 50]])

In [8]:
np.einsum('ijk,ijk->ij', a, b)

array([[ 5, 14],
       [23, 32],
       [41, 50]])

In [11]:
np.einsum('ijk,k->ij', a, b1)

array([[ 5, 14],
       [23, 32],
       [41, 50]])

### Run full list of parameters
Watch out: 20 or even 10 kills it
10 seems to work?

Single process shoots up to 12 gb memory

In [ ]:
%%time
assert(logfile==True) # Sanity Check
multi_run(hapsb_chrom, prms[:], processes = 8) # #For all ref: 4 for everything, 8 for 0.5x. For Europe only multiply x5

Running 100 total jobs; 8 in parallel.
Starting Pool of multiple workers...
Set Output Log path: ./Simulated/1000G_Mosaic/TSI5/lambda_rc1.0/ch3_4cm/output/iid0/chr3/default/hmm_run_log.txt
Set Output Log path: ./Simulated/1000G_Mosaic/TSI5/lambda_rc1.0/ch3_4cm/output/iid4/chr3/default/hmm_run_log.txt
Set Output Log path: ./Simulated/1000G_Mosaic/TSI5/lambda_rc1.0/ch3_4cm/output/iid8/chr3/default/hmm_run_log.txt
Set Output Log path: ./Simulated/1000G_Mosaic/TSI5/lambda_rc1.0/ch3_4cm/output/iid12/chr3/default/hmm_run_log.txtSet Output Log path: ./Simulated/1000G_Mosaic/TSI5/lambda_rc1.0/ch3_4cm/output/iid16/chr3/default/hmm_run_log.txt

Set Output Log path: ./Simulated/1000G_Mosaic/TSI5/lambda_rc1.0/ch3_4cm/output/iid24/chr3/default/hmm_run_log.txt
Set Output Log path: ./Simulated/1000G_Mosaic/TSI5/lambda_rc1.0/ch3_4cm/output/iid20/chr3/default/hmm_run_log.txt
Set Output Log path: ./Simulated/1000G_Mosaic/TSI5/lambda_rc1.0/ch3_4cm/output/iid28/chr3/default/hmm_run_log.txt
Set Output Log 

## Split up ground truth ROH into according folders
Takes about 30s for 600 prms

In [ ]:
%%time
### Split up ground truth roh.csv 
#(to pack into output folder as well for easier comparison)

for f in folders:
    for iid in iids[:]:
        for cutoff in cutoffs:
            #prefix_out = str(cutoff).replace(".", "") + "/"  
            #prefix_out="test/"
            path_out = os.path.join(f, "output", iid, "chr"+str(ch), prefix_out)
            split_up_roh_df(f, path_out, iid, 
                            file_in="roh_info.csv", 
                            file_out="roh_gt.csv")

# Run on downsampled individuals